### ISSUE TITLE
перевірка граматики: 2п

### ISSUE THREAD

**Issue by Rurych-Ivanna** [anrom7/CL_Project#13]
Здійснити аналіз за допомогою https://www.languagetool.org/uk/.
що нам робити з підкреслиними словами? для чого це робити?
і на цьому, і на другому сайті аналізумати відгуки повністю?

**Comment by anrom7** [comment]
Відгуки аналізувати повністю.
Аналіз робиться для того щоб у вас були факти для характеристики дискурсу.
