### ISSUE TITLE
Коректність роботи аналізатора

### ISSUE THREAD

**Issue by OlhaBulavkina** [anrom7/CL_Project#14]
"При знятті омонімії перевіряти коректність роботи програми морфологічного аналізу" - які саме помилки мається на увазі? Тобто в окремий файл треба кидати все те зайве, що видає аналізатор і те, що ми видалятимем у файлі із знятою омонімією?

**Comment by anrom7** [comment]
Якщо серед всіх варіантів (тегів), які запропонував аналізатор, на вашу думку, немає правильного то ви записуєте у окремий файл слово і той ваш правильний варіант (тег).

**Comment by anrom7** [comment]
відповідь на питання було обговорено на лекції
