### ISSUE TITLE
морфологічні характеристики 

### ISSUE THREAD

**Issue by Rurych-Ivanna** [anrom7/CL_Project#25]
Створити файл у який записати слова та теги морфологічних характеристик. Записати тільки ті слова, які проаналізував морфологічний аналізатор.

тобто, ті теги, які ми самі писали чи виправляли не мають бути у цьому файлі????

**Comment by anrom7** [comment]
слово - правильний варіант морф. хар.
слово - варіант програми (правильний варіант на вашу думку)
