### ISSUE TITLE
Коментарі на сайті

### ISSUE THREAD

**Issue by OlhaBulavkina** [anrom7/CL_Project#6]
Якщо на одному сайті є кілька сторінок коментарів, номерувати коментарі усі підряд, не залежно від сторінки чи на кожній сторінці кожен коментар матиме вже новий номер?

**Comment by anrom7** [comment]
Відгуки нумеруються для того щоб розрізняти відгуки одного автора, які він написав того самого дня. Наприклад автор "Джон" 21.12.2014 написав три відгуки. В такому випадку назви файлів будуть наступні Джон_21_12_2014_01.txt; Джон_21_12_2014_02.txt; Джон_21_12_2014_03.txt. Звідки ви взяли відгуки (декілька сторінок коментарів) ролі не грає. В назві тільки - автор, дата і порядковий номер. Якщо  Джон" 16.12.2014 написав один відгук а "Джек" так само один то назви будуть Джон_16_12_2014_01.txt; Джек_16_12_2014_01.txt.

**Comment by OlhaBulavkina** [comment]
А нумерувати їх треба так, як вони знаходяться на сайті: наприклад, Джон написав коментар другим після Джека, тоді він буде Джон_21_12_2014_02.txt чи цей номер означає який по рахунку коментар написав один автор?

**Comment by anrom7** [comment]
цей номер означає який по рахунку коментар написав один автор.
